# Generated by Django 4.1 on 2022-08-31 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('college_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='priority',
            field=models.CharField(choices=[('Urgent', 'Urgent'), ('Important', 'Important'), ('Basic', 'Basic')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='posted_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
